---
abstract: 'modify HTTP response headers'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Headers
requires:
  Plack::Middleware: 0
resources:
  bugtracker: https://github.com/nichtich/Plack-Middleware-Headers/issues
  homepage: https://github.com/nichtich/Plack-Middleware-Headers
  repository: https://github.com/nichtich/Plack-Middleware-Headers.git
version: 0.11
